config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :items
  resources :shipments, only: [:new, :create, :show]
  resources :shipment_items, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :shipment_items
  has_many :shipments, through: :shipment_items
  validates :title, :description, :unit_price, :stock, presence: true
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  has_many :shipment_items
  has_many :items, through: :shipment_items
  validates :customer_name, :email, presence: true
end

app/models/shipment_item.rb
class ShipmentItem < ApplicationRecord
  belongs_to :item
  belongs_to :shipment
  validates :quantity, :unit_price, :item_id, :shipment_id, presence: true

  def self.get_shipment_items(shipment)
    shipments = where(shipment_id: shipment.id)
  end 

  def self.find_existing(params)
    where(shipment_id: params["shipment_id"].to_i, item_id: params["item_id"].to_i)
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end 

  def new
  end 

  def create
    item = Item.new(item_params)
    if item.save
      flash[:notice] = "Item saved!" # this will show on the index page if the item was saved
      redirect_to items_path
    else
      flash[:notice] = "Item not created" # this will show on the new page if form entries are incomplete
      redirect_to new_item_path
    end 
  end

  def show
    @item = Item.find(params[:id])
  end 
  
  def edit
    @item = Item.find(params[:id])
  end 

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "Item updated!" 
      redirect_to item_path(@item)
    else  
      flash[:notice] = "Item not updated" 
      redirect_to edit_item_path(@item)
    end 
  end 
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy!
    redirect_to items_path
  end 

  private

  def item_params
    params.permit(:title, :description, :unit_price, :stock)
  end 
end 

app/controllers/shipment_items_controller.rb
class ShipmentItemsController < ApplicationController

  def create
    shipment_item_array = ShipmentItem.find_existing(shipment_item_params) # checks if there's already an existting shipment_item for the item
    if shipment_item_array.length > 0
      shipment_item = shipment_item_array.first
      shipment_item.update(quantity: (shipment_item.quantity + shipment_item_params["quantity"].to_i)) # increments the quantity if the shipment-item exists
    else 
      shipment_item = ShipmentItem.create(shipment_item_params) # creates the shipment item if it doesn't already exit
    end 

    item = Item.find_by(id: shipment_item.item_id)
    item.update(stock: (item.stock - params[:quantity].to_i)) # reduces the available stock of the item by the quantity of the shipment_item
    redirect_to shipment_path(shipment_item.shipment_id)
  end 

  private
  def shipment_item_params
    params.permit(:quantity, :unit_price, :item_id, :shipment_id)
  end 
end 

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  def new
  end 

  def create
    @shipment = Shipment.new(shipment_params)
    if @shipment.save
      flash[:notice] = "Shipment created!" # this will show on the index page if the item was saved
      redirect_to shipment_path(@shipment)
    else
      flash[:notice] = "Shipment not created" # this will show on the new page if form entries are incomplete
      redirect_to new_shipment_path
    end 
  end 

  def show
    @items = Item.all
    @shipment = Shipment.find(params[:id])
    @shipment_items = ShipmentItem.get_shipment_items(@shipment)
  end 

  private

  def shipment_params
    params.permit(:customer_name, :email)
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/edit.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %><br></div>
<% end %>
  
<h2>Update an item:</h2>
<%= form_with url: item_path(@item), method: :patch, local: true do |f| %>
  <%= f.label :title, "Item title:" %>
  <%= f.text_field :title, value: @item.title %><br><br>
  <%= f.label :description, "Item description:" %>
  <%= f.text_area :description, value: @item.description %><br><br>
  <%= f.label :unit_price, "Price per unit:" %>
  <%= f.number_field :unit_price, :step => 0.01, value: @item.unit_price %><br><br>
  <%= f.label :stock, "Quantity in stock:" %>
  <%= f.number_field :stock, min: 0, value: @item.stock %><br><br>
  <%= f.submit "Update item" %><br><br>
<% end %>    

app/views/items/index.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %><br></div>
<% end %>
  
<h2>Items Inventory</h2>

<% @items.each do |item| %>
  <%= link_to item.title, item_path(item) %><br>
  <%= item.description %><br>
  <%= item.unit_price %><br>
  <%= item.stock %><br><br>
<% end %>

<%= link_to "Create new item", new_item_path %><br>
<%= link_to "Create a shipment", new_shipment_path %>

app/views/items/new.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %><br></div>
<% end %>
  
<h2>Create a new item:</h2>

<%= form_with url: items_path, method: :post, local: true do |f| %>
  <%= f.label :title, "Item title:" %>
  <%= f.text_field :title %><br><br>
  <%= f.label :description, "Item description:" %>
  <%= f.text_area :description %><br><br>
  <%= f.label :unit_price, "Price per unit:" %>
  <%= f.number_field :unit_price, :step => 0.01 %><br><br>
  <%= f.label :stock, "Quantity in stock:" %>
  <%= f.number_field :stock, min: 0 %><br><br>
  <%= f.submit "Create item" %><br><br>
<% end %>    

app/views/items/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %><br></div>
<% end %>

<h2>Item Details:</h2>

<%= @item.title %><br>
<%= @item.description %><br>
<%= @item.unit_price %><br>
<%= @item.stock %><br><br>

<%= link_to "Edit this item", edit_item_path(@item) %><br>
<%= link_to "Delete this item", item_path(@item), method: :delete, data: { confirm: "Are you certain?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BackendInt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shipments/new.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %><br></div>
<% end %>
  
<h2>Create a new shipment:</h2>

<%= form_with url: shipments_path, method: :post, local: true do |f| %>
  <%= f.label :customer_name, "Customer name:" %>
  <%= f.text_field :customer_name %><br><br>
  <%= f.label :email, "Email address:" %>
  <%= f.text_field :email %><br><br>
  <%= f.submit "Create shipment" %><br><br>
<% end %> 

app/views/shipments/show.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %><br></div>
<% end %>

<h2>Shipment Details:</h2>

<%= @shipment.customer_name %><br>
<%= @shipment.email %><br>

<h2>Shipment items:</h2>

<% @shipment_items.each do |si| %>
  <div id="si-<%= si.id %>">
    <%= si.item[:title] %><br>
    Unit Price: <%= si.unit_price %><br>
    Quantity: <%= si.quantity %><br><br>
  </div>
<% end %> 

<h2>Add items:</h2>

<% @items.each do |item| %>
  <div id="item-<%= item.id %>">
    <%= link_to item.title, item_path(item) %><br>
    Description: <%= item.description %><br>
    Unit Price: <%= item.unit_price %><br>
    In Stock: <%= item.stock %><br>
      <%= form_with url: shipment_items_path, method: :post, local: true do |f| %>
        <%= f.label :quantity, "Quantity:" %>
        <%= f.number_field :quantity, in: 0..item.stock %>
        <%= f.hidden_field :unit_price, value: item.unit_price %>
        <%= f.hidden_field :item_id, value: item.id %>
        <%= f.hidden_field :shipment_id, value: @shipment.id %>
        <%= f.submit "Add to shipment" %><br><br>
      <% end %> 
  </div>
<% end %>